//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEulerDotNet.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpeedInfo", Namespace="http://traffictechnologysolutions.com/")]
    [System.SerializableAttribute()]
    public partial class SpeedInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeContextField;
        
        private int accessKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string timeContext {
            get {
                return this.timeContextField;
            }
            set {
                if ((object.ReferenceEquals(this.timeContextField, value) != true)) {
                    this.timeContextField = value;
                    this.RaisePropertyChanged("timeContext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int accessKey {
            get {
                return this.accessKeyField;
            }
            set {
                if ((this.accessKeyField.Equals(value) != true)) {
                    this.accessKeyField = value;
                    this.RaisePropertyChanged("accessKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://traffictechnologysolutions.com/", ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://traffictechnologysolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://traffictechnologysolutions.com/HelloWorld", ReplyAction="*")]
        ProjectEulerDotNet.ServiceReference1.HelloWorldResponse HelloWorld(ProjectEulerDotNet.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://traffictechnologysolutions.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectEulerDotNet.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ProjectEulerDotNet.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name speedResult from namespace http://traffictechnologysolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://traffictechnologysolutions.com/speed", ReplyAction="*")]
        ProjectEulerDotNet.ServiceReference1.speedResponse speed(ProjectEulerDotNet.ServiceReference1.speedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://traffictechnologysolutions.com/speed", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectEulerDotNet.ServiceReference1.speedResponse> speedAsync(ProjectEulerDotNet.ServiceReference1.speedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://traffictechnologysolutions.com/", Order=0)]
        public ProjectEulerDotNet.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ProjectEulerDotNet.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://traffictechnologysolutions.com/", Order=0)]
        public ProjectEulerDotNet.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ProjectEulerDotNet.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://traffictechnologysolutions.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class speedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="speed", Namespace="http://traffictechnologysolutions.com/", Order=0)]
        public ProjectEulerDotNet.ServiceReference1.speedRequestBody Body;
        
        public speedRequest() {
        }
        
        public speedRequest(ProjectEulerDotNet.ServiceReference1.speedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://traffictechnologysolutions.com/")]
    public partial class speedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int key;
        
        public speedRequestBody() {
        }
        
        public speedRequestBody(int key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class speedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="speedResponse", Namespace="http://traffictechnologysolutions.com/", Order=0)]
        public ProjectEulerDotNet.ServiceReference1.speedResponseBody Body;
        
        public speedResponse() {
        }
        
        public speedResponse(ProjectEulerDotNet.ServiceReference1.speedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://traffictechnologysolutions.com/")]
    public partial class speedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjectEulerDotNet.ServiceReference1.SpeedInfo speedResult;
        
        public speedResponseBody() {
        }
        
        public speedResponseBody(ProjectEulerDotNet.ServiceReference1.SpeedInfo speedResult) {
            this.speedResult = speedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ProjectEulerDotNet.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ProjectEulerDotNet.ServiceReference1.WebServiceSoap>, ProjectEulerDotNet.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectEulerDotNet.ServiceReference1.HelloWorldResponse ProjectEulerDotNet.ServiceReference1.WebServiceSoap.HelloWorld(ProjectEulerDotNet.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ProjectEulerDotNet.ServiceReference1.HelloWorldRequest inValue = new ProjectEulerDotNet.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProjectEulerDotNet.ServiceReference1.HelloWorldRequestBody();
            ProjectEulerDotNet.ServiceReference1.HelloWorldResponse retVal = ((ProjectEulerDotNet.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectEulerDotNet.ServiceReference1.HelloWorldResponse> ProjectEulerDotNet.ServiceReference1.WebServiceSoap.HelloWorldAsync(ProjectEulerDotNet.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectEulerDotNet.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ProjectEulerDotNet.ServiceReference1.HelloWorldRequest inValue = new ProjectEulerDotNet.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProjectEulerDotNet.ServiceReference1.HelloWorldRequestBody();
            return ((ProjectEulerDotNet.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectEulerDotNet.ServiceReference1.speedResponse ProjectEulerDotNet.ServiceReference1.WebServiceSoap.speed(ProjectEulerDotNet.ServiceReference1.speedRequest request) {
            return base.Channel.speed(request);
        }
        
        public ProjectEulerDotNet.ServiceReference1.SpeedInfo speed(int key) {
            ProjectEulerDotNet.ServiceReference1.speedRequest inValue = new ProjectEulerDotNet.ServiceReference1.speedRequest();
            inValue.Body = new ProjectEulerDotNet.ServiceReference1.speedRequestBody();
            inValue.Body.key = key;
            ProjectEulerDotNet.ServiceReference1.speedResponse retVal = ((ProjectEulerDotNet.ServiceReference1.WebServiceSoap)(this)).speed(inValue);
            return retVal.Body.speedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectEulerDotNet.ServiceReference1.speedResponse> ProjectEulerDotNet.ServiceReference1.WebServiceSoap.speedAsync(ProjectEulerDotNet.ServiceReference1.speedRequest request) {
            return base.Channel.speedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectEulerDotNet.ServiceReference1.speedResponse> speedAsync(int key) {
            ProjectEulerDotNet.ServiceReference1.speedRequest inValue = new ProjectEulerDotNet.ServiceReference1.speedRequest();
            inValue.Body = new ProjectEulerDotNet.ServiceReference1.speedRequestBody();
            inValue.Body.key = key;
            return ((ProjectEulerDotNet.ServiceReference1.WebServiceSoap)(this)).speedAsync(inValue);
        }
    }
}
